# This is a basic workflow to help you get started with Actions

name: GitHub Actions Secret Example

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  secrets-in-github-actions:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       # Runs a single command using the runners shell
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "The GitHub Action Secret will be masked: "
          echo ${{ secrets.SECRET_TOKEN }}
          echo "Trick to echo GitHub Actions Secret: "
          echo ${{secrets.SECRET_TOKEN}} | sed 's/./& /g'
      - name: Step 2 - GitHub Action if statement (true)
        env: 
          WHO_TO_TRUST: ${{ secrets.SECRET_TOKEN }}
        if: env.WHO_TO_TRUST == 'TrustNo1'
        run: echo "I know what the secret token is!"
        
      - name: Step 3 - Conditiona GitHub Aciton (false)
        shell: bash
        env:
          WHO_TO_TRUST: ${{ secrets.SECRET_TOKEN }}
        if: env.WHO_TO_TRUST != 'TrustNobody'
        run: echo "I was wrong thinking the GitHub secret was 'TrustNobody'!"
          
